on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: localpropetries
        shell: bash
        env:
          maps_api_key: ${{secrets.MAPS_API_KEY}}
        run: echo MAPS_API_KEY="$maps_api_key" >> /home/runner/work/QRHunter/QRHunter/local.properties

      - uses: actions/checkout@v2
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
      - run: npm install -g firebase-tools
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: firebase emulators:exec "./gradlew build --stacktrace"
      - name: Run Unit Tests
        run: firebase emulators:exec "./gradlew test --stacktrace"
